services:
  - type: web
    name: django-websocket-app
    env: python
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      daphne -b 0.0.0.0 -p $PORT WebSocket.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DJANGO_SETTINGS_MODULE
        value: WebSocket.settings
      - key: django-insecure-c^nxqc&96#=t2imn^l=z31r745%xy^qlmvck^boxrd%lqw#!i*
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString

databases:
  - name: postgres
    plan: free
    databaseName: postgres
    user: postgres.oehhqcwblkcimavufypy